_add_to_path() {
	local d="$1"

  if [[ -d "$d" && ":$PATH:" != *":$d:"* ]]; then
    PATH="$1${PATH:+":$PATH"}"
  fi
}

_add_to_path /opt/homebrew/bin
_add_to_path "${HOME}/go/bin"
_add_to_path "${HOME}/.cargo/bin"
_add_to_path "${HOME}/.local/bin"

unset _add_to_path