source <(antibody init)
antibody bundle < "${HOME}/.zplugins"

source "${HOME}/.zmodules/aliases.zsh"
source "${HOME}/.zmodules/fzf.zsh"
source "${HOME}/.zmodules/git.zsh"
source "${HOME}/.zmodules/navigation.zsh"

[[ -f "${HOME}/.zshrc.local" ]] && source "${HOME}/.zshrc.local"
