source <(antibody init)

export EDITOR=nvim
export VISUAL="${EDITOR}"

antibody bundle < "${HOME}/.zplugins"

source "${HOME}/.zmodules/aliases.zsh"
source "${HOME}/.zmodules/fzf.zsh"
source "${HOME}/.zmodules/history.zsh"
source "${HOME}/.zmodules/git.zsh"
source "${HOME}/.zmodules/navigation.zsh"

[[ -f "${HOME}/.zshrc.local" ]] && source "${HOME}/.zshrc.local"
